{% set name = "qpd" %}
{% set version = "0.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpd-{{ version }}.tar.gz
  sha256: 61aa2046363a94e9efdd97def76f11fa20f4a108c1c235d2700a5920b76bab4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - adagio
    - antlr4-python3-runtime
    - pandas >=1.0.2
    - python >=3.6
    - sqlalchemy
    - triad

test:
  source_files:
    - tests
  imports:
    - qpd
    - qpd_dask
    - qpd_pandas
    - qpd_ray
    - qpd_test
    - qpd_version
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - cloudpickle >=1.4.0
    - dask
    - modin-ray
    - pandas >=1.1.2
    - pandasql
    - pip
    - pytest    

about:
  home: https://pypi.org/project/qpd/
  summary: Query Pandas Using SQL
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
