{% set name = "qpd" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0ed05b88e321ea9935874377bda11339c90f1469f34344e9b41d16b8088e136

build:
  number: 0
  # s390x is missing triad  
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - adagio
    - antlr4-python3-runtime >=4.11.1,<4.12
    - pandas >=1.2.0
    - python
    - triad >=0.9.0

test:
  imports:
    - qpd
    - qpd_dask
    - qpd_pandas
    # modin-ray and ray-default: no support for python 3.11 and missing on all archs except for linux-64 and win-64  
    - qpd_ray  # [py<311 and (linux64 or win)]
    - qpd_test
    - qpd_version
  requires:
    - pip
    - cloudpickle >=1.4.0
    - dask
    # modin-ray and ray-default: no support for python 3.11 and missing on all archs except for linux-64 and win-64
    - modin-ray >=0.8.1.1  # [py<311 and (linux64 or win)]
  commands:
    - pip check 

about:
  home: https://pypi.org/project/qpd/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Query Pandas Using SQL
  description: |
    QPD let you run the same SQL (SELECT for now) statements on different computing 
    frameworks with pandas-like interfaces. Currently, it support Pandas, Dask and 
    Ray (via Modin on Ray). QPD directly translates SQL into pandas-like operations 
    to run on the backend computing frameworks, so it can be significantly faster 
    than some other approaches, for example, to dump pandas dataframes into SQLite, 
    run SQL and convert the result back into a pandas dataframe. However, the top 
    priorities of QPD are correctness and consistency. It ensures the results of 
    implemented SQL features following SQL convention, and it ensures consistent 
    behavior regardless of backend computing frameworks. 
  doc_url: https://pypi.org/project/qpd/

extra:
  recipe-maintainers:
    - charlesbluca
    - kvnkho
    - goodwanghan
    - thewchan
