{% set name = "qpd" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpd-{{ version }}.tar.gz
  sha256: aee56782ed22eb70f0308cbff1cc009b7d258b0c2c9a9e5abe0bc8bc413b0cd1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - adagio
    - antlr4-python3-runtime >=4.10
    - pandas >=1.0.2
    - python >=3.6,<3.9
    - sqlalchemy
    - triad

test:
  source_files:
    - tests
  imports:
    - qpd
    - qpd_dask
    - qpd_pandas
    - qpd_ray
    - qpd_test
    - qpd_version
  commands:
    - pip check
    # Comment out test suite until ray issue resolved
#     - pytest -vvv --capture=tee-sys tests
  requires:
    - cloudpickle >=1.4.0
    - dask
    - modin-ray
    - pandas >=1.1.2
#     - pandasql
    - pip
#     - pytest    

about:
  home: https://pypi.org/project/qpd/
  summary: Query Pandas Using SQL
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - charlesbluca
    - kvnkho
    - goodwanghan
    - thewchan
